AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - vendor/bundle/**/*

require:
 - rubocop-rspec
 - rubocop-performance

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Max: 20
