AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - vendor/bundle/**/*

require:
 - rubocop-rspec
 - rubocop-performance
 - rubocop-rake

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 4

Metrics/ParameterLists:
  Enabled: false
